export const DEFAULT_SIDEBAR_WIDTH = '16.5625rem';
export const DEFAULT_MINI_SIDEBAR_WIDTH = '5rem';
export const DEFAULT_HEADER_HEIGHT = '5.25rem';
export const DEFAULT_FOOTER_HEIGHT = '2.25rem';
export const DEFAULT_DIALOG_CONTENT_MAX_HEIGHT = '70vh';
export const NOTIFICATION_CENTER_WIDTH = 500;
export const NOTIFICATION_CENTER_HEIGHT = 600;
export const DEFAULT_PAGE_SIZE = 10;
export const DEFAULT_LAZY_OPTIONS_COUNT = 100;
export const DEFAULT_FILTER_SIZE = 400;
export const DEFAULT_TABLE_POLLING_INTERVAL = 30000;
export const DEFAULT_STATUS_POLLING_INTERVAL = 15000;
export const INFINITE_PAGE_SIZE = 2147483647;
export const DEFAULT_INPUT_DEBOUNCE = 800;
export const DEFAULT_ALERT_AUTOHIDE_DURATION = 5000;
export const DEFAULT_UPLOAD_STATUS_INTERVAL = 3000;

export const SERVER_DATE_FORMAT = 'YYYY-MM-DDTHH:mm:ss';
export const SERVER_DATETIME_FORMAT = 'YYYY-MM-DDTHH:mm:ss';

export const DEFAULT_DATE_FORMAT = 'DD/MM/YYYY';
export const DEFAULT_DATE_APM_FORMAT = 'DD/MM/YYYY A';
export const DEFAULT_DATETIME_FORMAT = 'DD/MM/YYYY HH:mm:ss';
export const DEFAULT_DATETIME_APM_FORMAT = 'DD/MM/YYYY hh:mm A';
export const MAX_DATE_FOR_TIME_AGO = 2;