export enum ModuleCode {
  TEST = 'TEST'
}

enum TaskCode {
  TRAINER_REGISTER = 'TRAINER_REGISTER',
  CANCEL_COURSE = 'CANCEL_COURSE',
  DELETE_COURSE = 'DELETE_COURSE',
  EDIT_COURSE = 'EDIT_COURSE',
  APPROVE_COURSE = 'APPROVE_COURSE',
  APPROVE_EDIT = 'APPROVE_EDIT',
  START_COURSE = 'START_COURSE',
  CONFIRM_PASSED_PARTICIPANTS = 'CONFIRM_PASSED_PARTICIPANTS',
  FINISH_COURSE = 'FINISH_COURSE',
  APPROVE_CANCEL_COURSE = 'APPROVE_CANCEL_COURSE',
  UPLOAD_MOF_RESULT = 'UPLOAD_MOF_RESULT'
}

export default TaskCode;